services:
  speedscope-service:
    image: ghcr.io/weirdgloop/speedscope-service:main
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - "./db:/db:rw"
    logging:
      driver: journald
      options:
        tag: "{{.Name}}/{{.ID}}"
